#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

files=$(git diff --name-only --cached --diff-filter=d '*.js' '*.jsx')

if [ "$files" ] ; then
npx prettier --check $files;
npx eslint $files;
fi;

npm run test
